spring.application.name=catalog
server.port=${PORT:8081}

#Cambia il banner con la seguente properties
spring.banner.location=classpath:/banner.txt

# Database MySQL
#OnLine
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#LOCALE
#spring.datasource.url=jdbc:mysql://localhost:3306/catalog?useSSL=false&serverTimezone=Europe/Rome
#spring.datasource.username=root
#spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Vaadin
vaadin.productionMode=false
#spring.devtools.restart.enabled=true
#spring.devtools.livereload.enabled=true
#vaadin.launch-browser-on-startup=true
#vaadin.developer.mode=true


#app configuration

path.root=G:
#path.root=H:\backup
